packages:
  - "."

onlyBuiltDependencies:
  - esbuild
  - svelte-preprocess

allowBuilds:
  esbuild: true
  sharp: set this to true or false
  svelte-preprocess: true
  workerd: set this to true or false
